#!/usr/bin/env bash

cd ~/zz/searchex

mix escript.build               > /dev/null 2>&1
echo "y" | mix escript.install  > /dev/null 2>&1

sudo rm -rf ~/.searchex/sample

searchex version

searchex fetch elixir-search/sample > /dev/null 2>&1

list=`searchex ls`

echo "COLLECTION LIST"
echo $list

for file in $list; do
  COLL=$file bats test/bats/base.bats
done

searchex info

